RAYS_COUNT = 5


# +2 for car_speed, car_angle
# +2 for Action {steering, acceleration}
NUM_DEFAULT_INPUT_NEURONS = 4

NETWORK = [NUM_DEFAULT_INPUT_NEURONS + RAYS_COUNT, 2, 1]

COLLISION_PENALTY = 0 * 1e0
HEADING_REWARD = 0 * 1e-1
WRONG_HEADING_PENALTY = 0 * 1e0
IDLENESS_PENALTY = 32 * 1e-1
SPEEDING_PENALTY = 32 * 1e-1
MIN_SPEED = 0.1 * 1e0
MAX_SPEED = 0.7 * 1e0